name = "Lattice"
uuid = "d3735f9f-9cdb-4984-9fa1-47b4d39f9b75"
authors = ["Pietro Butti <pietro.butti.fl@gmail.com>"]
version = "0.1.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
Revise = "3.6.2"
